export const GET_DATA_REQUEST=' GET_DATA_REQUEST';
export const GET_DATA_SUCCESS=' GET_DATA_SUCCESS';
export const GET_DATA_ERROR=' GET_DATA_ERROR';

export const ADD_DATA_REQUEST=' ADD_DATA_REQUEST';
export const ADD_DATA_SUCCESS=' ADD_DATA_SUCCESS';
export const ADD_DATA_ERROR=' ADD_DATA_ERROR';

export const UPDATE_DATA_REQUEST=' UPDATE_DATA_REQUEST';
export const UPDATE_DATA_SUCCESS=' UPDATE_DATA_SUCCESS';
export const UPDATE_DATA_ERROR=' UPDATE_DATA_ERROR';

export const DELETE_DATA_REQUEST=' DELETE_DATA_REQUEST';
export const DELETE_DATA_SUCCESS=' DELETE_DATA_SUCCESS';
export const DELETE_DATA_ERROR=' DELETE_DATA_ERROR';

export const ADD_CART_DATA_REQUEST=' ADD_CART_DATA_REQUEST';
export const ADD_CART_DATA_SUCCESS=' ADD_CART_DATA_SUCCESS';
export const ADD_CART_DATA_ERROR=' ADD_CART_DATA_ERROR';

export const GET_CART_DATA_REQUEST=' GET_CART_DATA_REQUEST';
export const GET_CART_DATA_SUCCESS=' GET_CART_DATA_SUCCESS';
export const GET_CART_DATA_ERROR=' GET_CART_DATA_ERROR';

export const DELETE_CART_DATA_REQUEST=' DELETE_CART_DATA_REQUEST';
export const DELETE_CART_DATA_SUCCESS=' DELETE_CART_DATA_SUCCESS';
export const DELETE_CART_DATA_ERROR=' DELETE_CART_DATA_ERROR';


export const ADD_WISH_DATA_REQUEST=' ADD_WISH_DATA_REQUEST';
export const ADD_WISH_DATA_SUCCESS=' ADD_WISH_DATA_SUCCESS';
export const ADD_WISH_DATA_ERROR=' ADD_WISH_DATA_ERROR';

export const GET_WISH_DATA_REQUEST=' GET_WISH_DATA_REQUEST';
export const GET_WISH_DATA_SUCCESS=' GET_WISH_DATA_SUCCESS';
export const GET_WISH_DATA_ERROR=' GET_WISH_DATA_ERROR';

export const DELETE_WISH_DATA_REQUEST=' DELETE_WISH_DATA_REQUEST';
export const DELETE_WISH_DATA_SUCCESS=' DELETE_WISH_DATA_SUCCESS';
export const DELETE_WISH_DATA_ERROR=' DELETE_WISH_DATA_ERROR';